apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitea
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
# - secret.yaml
# - httpscaled-object.yaml
