# apiVersion: v1
# kind: Secret
# metadata:
#     name: seafile-secret
#     namespace: seafile
# type: Opaque
# stringData:
#     JWT_PRIVATE_KEY: ""
#     DB_PASSWORD: ""
#     DB_ROOT_PASSWD: ""
#     INIT_SEAFILE_ADMIN_PASSWORD: ""
