---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - require-resource-limits.yaml
  - require-labels.yaml
# - require-security-context.yaml
# - prevent-privileged-containers.yaml
# - prevent-latest-tag.yaml
# - require-network-policy.yaml
# - auto-add-security-context.yaml
# - verify-flux-git-repositories.yaml
# - verify-flux-images.yaml
# - verify-flux-sources-in-cel.yaml
# - detect-non-flux-objects.yaml
# - pod-security-baseline-standards.yaml
# - pod-security-restricted.yaml
# - podsecurity-subrule-restricted-capabilities.yaml
# - podsecurity-subrule-restricted-seccomp.yaml
