apiVersion: v1
kind: Secret
metadata:
  name: gitea-authentik-secret
  namespace: gitea
type: Opaque
stringData:
  key: u4QfKMnaRrcfipiNKOnrihhhA5U9Ik8shlhTviL6
  secret: UuWVUFWxY2Z9CA2F9BLNSnw4zpY46V84MTXMSGe6Tslx8h2y8rWefZIspMsvVQ97zKH0UnJlVepU2RmGdhiMjzMeY1i9AuKZzMrAIAKqBFGYqnT1nxUuT1GANDWds1RP
