---
- name: Ensure qcow directory exists
  ansible.builtin.file:
    path: /var/lib/vz/template/qcow
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Include Debian tasks
  ansible.builtin.include_tasks: 'debian.yaml'

- name: Include Alpine tasks
  ansible.builtin.include_tasks: 'alpine.yaml'

- name: Include LXC tasks
  ansible.builtin.include_tasks: 'lxc.yaml'
